### ISSUE TITLE
desperated help! - recover from changes0.json

### ISSUE THREAD

**Issue by georgew21** [ONLYOFFICE/DesktopEditors#1127]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

last

### Expected Behavior

Hello,

My pc had a shutdown and I lost a very important part of my document. When I opened again onlyoffice, it failed to recover my file.

### Actual Behavior

Browsing on a folder recover in where was my document, I found there a file with name **changes0.json.**

**Is there any way to recover my written text from this file??**

Its' very important for my job...

thanks for any help.

**Comment by LuckySpecialist** [comment]
Hello @georgew21!
Please, send the contents of the `recovery` folder in the ZIP archive to the email **files@onlyoffice.com**, marked `files for github issue 1127` and a [link](https://github.com/ONLYOFFICE/DesktopEditors/issues/1127) in the body of the letter
Write a message when you send an email with files and specify the version of the application, that you used when the problem occurred.
We'll see if something can be restored.

**Comment by HectorB-2020** [comment]
Having worked with Only Office editors I develop a habit to
1. regularly press `Ctrl`-`S` to save documents;
2. make backup copies of documents being edited, treat them as snapshots.

The reason for such behaviour which presumably could look like paranoia is that Only Office applications crash at least 10 times a day. Now it's better since I know conditions when application is likely to crash and I've learnt to avoid it. :smile: 

Anyway, I noticed an interesting behavior, not for the first time.

Like I said, I'm convinced that I always have a saved copy on disk.
Recently the editor crashed.
All right, no worries I thought - I've got a copy made with `Ctrl`-`S` a few minutes ago.
I found that file among recent ones and clicked to open it.

I cannot describe how I was shocked to find that it opened a file with changes dated probably yesterday. I attempted to recover this file; yes, its name was in the list of files that application believed could be recovered.
But it opened that same old file. :fearful: Guys, at that moment I truly believed I was going to have a heart attack.

But I opened the folder where that file resided. Thankfully :exploding_head: the file was exactly the one which I saved a few minutes before the crash.

Dear Only Office reps!
Could you explain why "Open file" opened the old file?

**Comment by LuckySpecialist** [comment]
Hi @HectorB-2020!
Maybe it's better not to look for workarounds and start a separate issue, figure it out and solve it in future releases?
> Could you explain why "Open file" opened the old file?
Do you mean opening files from the recent list? Is the file local or from the portal?

**Comment by HectorB-2020** [comment]
@LuckySpecialist, the separate issue has been here for three weeks now #1091. The mentioned workaround is also there. In my view this is closely related to another issue with `undefined`: https://github.com/ONLYOFFICE/DocumentServer/issues/1976.

Still I'm certainly thinking about creating an issue why Only Office opens old files. Does it dig them from old recoveries? It's only an educated guess. :smile:

**Comment by LuckySpecialist** [comment]
@HectorB-2020, then it is better for you to write in the topic corresponding to the problem, so as not to confuse others.
In addition, your single scenario can lead to several different errors, so creating separate issues, related to it, can increase the solution time.
Thanks for understanding.

**Comment by HectorB-2020** [comment]
@LuckySpecialist 

> Do you mean opening files from the recent list? Is the file local or from the portal?

Ironically something resembling was reported about two year ago. I'm now skimming through issues here to find something useful.
But the most amusing part of that story, that one of these guys who reported that issue was me. :rofl: Frankly I completely forgot about that.
Watch this:
* #528
* #550
It's a shame nobody took these issues seriously. :sob:

**Comment by erikbucik** [comment]
Hi @LuckySpecialist, I have a similar issue.

I was editing a local document with the ONLYOFFICE Desktop Editor on my Windows10 laptop when the app suddenly terminated the session. Unfortunately I don't have a screenshot, but the document editing window became blank with a message in the center that said something like "Session terminated, possibly due to a lack of memory". (In this state it is still possible to open/create new documents, but saving the 'terminated' one is impossible.)

I have the Autorecover feature enabled, so I checked the files and noticed that the `changes0.json` shows the "last modified date" about an hour later than the time the document was opened. If I try an open that `json` with a notepad I see only a very long string of random characters.

**How can I check what changes were actually saved?**
_And is it possible to set some sort of an Auto-save on local document files?_

**Comment by LuckySpecialist** [comment]
Hi @erikbucik I apologize for the late response, but if your document suddenly closed, you need to restart the editors so that the files for recovery appear in the list.
After that, you will be able to open it with changes that have not been saved before.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
