### ISSUE TITLE
Broken installation path in Windows MSI installer

### ISSUE THREAD

**Issue by Ben1138** [ONLYOFFICE/DesktopEditors#1157]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.2.1

### Expected Behavior

I expected the `MANUFACTURER_INSTALL_FOLDER` property to be set to a sensible value in the msi installer.

### Actual Behavior

The property is most likely not set and falls back to the property name itself.

![grafik](https://user-images.githubusercontent.com/8263806/207297978-714ce6b9-6790-4174-b5e9-313b5f07a873.png)

### Reproduction Steps

- Download x64 MSI installer for Windows 11 / 10 / 8.1 / 8 / 7
- Run it and step forward to the installation folder selection

### Additional information

I'm actually on Windows 11, but the bug report OS combo box only has an entry for "_Windows 10 / 8.1 / 7_".

The x86 MSI installer is affected aswell. The EXE installers (both x64 and x86) seem to be fine though.

**Comment by DAumkraft** [comment]
Greetings, @Ben1138!
Thanks for writing about this problem!
This is a serious problem and I created a bug in our internal bugtracking system. The problem will be fixed in an upcoming release.
For now, you can try other solutions to the problem:
1. Use the exe installer
2. Install the program from the msi using the command line, adding the parameter `productlanguage=1033` after `DesktopEditors_x86.msi`. This will run the installation in English, which does not have this problem. After installation you can select the German language in the settings.

**Comment by DenisDeeSign** [comment]
DesktopEditors v7.3.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
