### ISSUE TITLE
OnlyOffice adds &amp; in formula when ods-file is created with LibreOffice

### ISSUE THREAD

**Issue by ErikSteiner** [ONLYOFFICE/DesktopEditors#1171]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

7.2.1

### Expected Behavior

There should be no difference between both programs in such a simple case.

### Actual Behavior

However, every `&` is escaped like this.

### Reproduction Steps

1. Open LibreOffice Calc
2. Create a formula in a random cell like `=COLUMN(INDIRECT(C20&"1"))`, where C20 contains the letter `S`
3. Save the file and open it with OnlyOffice
4. OnlyOffice shows the formula like this:
   `=COLUMN(INDIRECT(C20&amp;"1"))`

### Additional information

**LibreOffice**
Version: 7.3.7.2 / LibreOffice Community
Build ID: 30(Build:2)
CPU threads: 24; OS: Linux 5.15; UI render: default; VCL: gtk3
Locale: de-DE (de_DE.UTF-8); UI: de-DE
7.3.7-2
Calc: threaded

**Comment by rsnegirev** [comment]
Hi @ErikSteiner 

Sorry for so long answer, we probably lost this issue.

I've checked this behavior in the current release version 7.4.1.36 and now it works correctly.

It was fixed in version 7.3, this is the commit:
https://github.com/ONLYOFFICE/web-apps/commit/7a11ecd7d73556cc62750ced640db247c30ea59d
