### ISSUE TITLE
Later added table column protrudes beyond document

### ISSUE THREAD

**Issue by Atalanttore** [ONLYOFFICE/DesktopEditors#1185]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.1.36

### Expected Behavior

The existing columns should shrink to make space for the new rightmost column.

### Actual Behavior

The rightmost table column added later protrudes beyond the document.

### Reproduction Steps

1. Set page orientation to landscape format
2. Add a table with 2 columns.
3. Select the right column.
4. Right-click on it to open the context menu.
5. Add another column to the right of it.

### Additional information

Document visualizing the issue: [Later_added_table_column_protrudes_beyond_document.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/10472255/Later_added_table_column_protrudes_beyond_document.docx)

---

I have installed OnlyOffice not as DEB package but as Flatpak. Only the native package format of my operating system (Linux Mint) is DEB.

**Comment by ElenaMaaya** [comment]
Hello, @Atalanttore!
Thank you for report!
The problem is in the table settings. 
The checkbox "Automatically resize to fit contents" is disabled. (screenshot). After activating this option problem is gone.

This option is enabled by default when adding a table. 
Please, add a new table and see if this option is there.
The issue does not reproduce with a new table . (Kubuntu 22.04 and Windows 11).
I'm waiting for your feedback.
![table](https://user-images.githubusercontent.com/96118677/219038137-928a1cd3-db38-4782-8b18-aa7d0b38ada2.jpg)

**Comment by Atalanttore** [comment]
Hi @ElenaMaaya

In the meantime, OnlyOffice has been updated to version 7.3.0 on my computer.

The given problem does not occur anymore with version 7.3.0.

Was the issue fixed in version 7.3.0 or is it a coincidence?

**Comment by ElenaMaaya** [comment]
Hey @Atalanttore!
This is great news!
I have the correct behavior of this option in version 7.2.1 and 7.3.0. 
Maybe the problem was an accident or incorrect table settings.
I'm happy to help!
