### ISSUE TITLE
Add ability to change orientation per-page

### ISSUE THREAD

**Issue by yllekz** [ONLYOFFICE/DesktopEditors#1288]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hello, I noticed a feature in Word that is not available in OnlyOffice.

In Word, one has the ability to set page orientation on a per-page or per-content basis. In OnlyOffice, there seems to be no way to do this as there are no page setup dialog boxes or "apply to selected text" equivalents.

See [this article](https://www.howtogeek.com/775304/how-to-make-only-one-page-landscape-in-a-word-document/) for reference.

Can this be added?

**Comment by maruacat** [comment]
Hello, @yllekz 
In the OnlyOffice editor, you can also set the orientation for one or more pages in a document when using a section break (the method is similar to the second method in the article you attached).
So, to change the orientation of a specific page in a document, you must do the following:
1. Set the cursor to the beginning of the page whose orientation you want to change
2. Go to the top menu > "Layout" tab > click the arrow on the "Breaks" button to open the drop-down list > select "Insert section break" > "Continuous page"
3. Staying in the tab "Layout" press the button "Orientation" > "Landscape"
As a result of the performed actions, the orientation of the current and following pages will be changed to Landscape.
To return the portrait orientation, you must repeat steps 1 and 2, and at step 3, when you press the "Orientation" button, select "Portrait".
I am attaching a video showing how to do it 
[Screencast from 05-11-2023 03:11:15 PM.webm](https://github.com/ONLYOFFICE/DesktopEditors/assets/103575766/0ebb5f6a-47c1-4b24-9619-cd15ec0a8617)

Thank you for your feedback and have a nice day!

**Comment by DenisDeeSign** [comment]
This issue was closed due to no response.

**Comment by CharifMah** [comment]
When setting a single page to landscape orientation (similar to Microsoft Word), the footer layout and page numbering break on the page following the landscape section.

Specifically, after inserting a landscape page within a portrait document, the footer on the next page is no longer rendered correctly or becomes misaligned. Additionally, page numbers may reset, disappear, or display incorrectly after the landscape section.

Steps to reproduce:

Create a document with portrait orientation.

Insert a section break and change one page to landscape.

Continue with portrait orientation on the next page.

Observe that the footer and page numbering on the page after the landscape section are broken or inconsistent.

Expected behavior:
The footer and page numbering should remain consistent and correctly formatted across all pages, including those following a landscape section.
