### ISSUE TITLE
New created sheet using right click menu can't be opened in MS Office

### ISSUE THREAD

**Issue by w202mg** [ONLYOFFICE/DesktopEditors#1356]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

7.4.1.36

### Expected Behavior

After creating a new sheet file in a folder using the right-click menu the file shall be opened or in OnlyOffcie or in MS Office.

### Actual Behavior

MS Office can't open new sheet files.

### Reproduction Steps

1. Install MS Office
2. Install OnlyOffice
3. Create a new sheet file using the right-click menu
4. Try to open the file in MS Excel

### Additional information

Would be nice if during the installation OnlyOffice would ask if the user wishes to update the right-click menu. Last time I could fix it only by repairing of MS Office.

**Comment by LuckySpecialist** [comment]
Hi @w202mg, this problem already fixed in https://github.com/ONLYOFFICE/desktop-apps/pull/807 and included in next major release.
The problem with deleting values from the registry was fixed earlier https://github.com/ONLYOFFICE/desktop-apps/pull/576 and included in version 7.3, therefore, there is no need to make such an option.
Thanks for the feedback.

**Comment by Rita-Bubnova** [comment]
DesktopEditors v7.5.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
