### ISSUE TITLE
Interface is very slow

### ISSUE THREAD

**Issue by qlofly** [ONLYOFFICE/DesktopEditors#1378]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package), Linux (RPM package)

### Version information

7.4.1

### Expected Behavior

I used to use Fedora gnome on wayland and everything was fine.

### Actual Behavior

After switching to EndeavourOs + Sway, the office began to work very slowly. Loading and the interface respond from 20 seconds to several minutes. Sometimes there was an error similar to "oops, something went wrong."

OS: EndeavourOS Linux x86_64
Kernel: 6.1.47-1-lts
Resolution: 1920x1080
WM: sway
CPU: 11th Gen Intel i5-1155G7 (8) @ 4.500GHz
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics]
Memory: 7648MiB

### Reproduction Steps

Just interaction with the interface..

### Additional information

![fdvfd](https://github.com/ONLYOFFICE/DesktopEditors/assets/64271543/1f050e4d-ad6d-4006-b423-793aa2d4ed41)

I've tried various options by adding variables before running, like here https://github.com/ONLYOFFICE/DesktopEditors/issues/382
but it didn't help

**Comment by qlofly** [comment]
The fix turned out to be a rollback to the previous working version, the new one still does not work as it should.
sudo flatpak update --commit=6ae98cba3421104f2284ff31ea702d254d1561e6d127d22cf6cb562d21079ce6 org.onlyoffice.desktopeditors

**Comment by pjkaufman** [comment]
I am seeing this issue on sway 1.7 on Pop OS! 22.04. I am not sure what is going on with it. It seems that for some reason it takes up a lot of CPU resources when I try to type things and it just sits there stalling out. I really would like to continue using OnlyOffice. So I would be happy to help out in any way I can.

Running `sudo flatpak update --commit=6ae98cba3421104f2284ff31ea702d254d1561e6d127d22cf6cb562d21079ce6 org.onlyoffice.desktopeditors` was able to update to an older version of flatpak. However it did not work for me since it failed to start. It said something about `wayland` not being in some list.

**Comment by piater** [comment]
Same here, running sway 1.8 under Arch LInux, and onlyoffice 7.5.0 from the released onlyoffice-desktopeditors_amd64.deb (via the AUR).

It starts fine, but any user interaction, even just moving the mouse pointer into the onlyoffice window, causes CPU load to explode, and onlyoffice is unusably slow.

FWIW, strace spews lots of
```
recvmsg(36, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
```
for two different sockfds.

**Comment by HishamAHai** [comment]
I have the same issue on hyprland
At first I thought that the culprit was my nvidia gpu, which is to be blamed of course
But also, the software is still using xwayland, and the only solution will be to rewrite it to become wayland native

**Comment by Sal-Kal** [comment]
Facing the same issue on Sway version 1.9 running on Ubuntu 24.04.3 LTS.

Only Office Version: 8.3.3.21

Installed via Debian file.
