### ISSUE TITLE
Impossible to input number range - it gets turned into a date format

### ISSUE THREAD

**Issue by K0-RR** [ONLYOFFICE/DesktopEditors#1484]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows XP / Vista, Windows 10 / 8.1 / 7, macOS 10.11 x86, macOS 10.12 or higher, Linux (DEB package), Linux (RPM package)

### Version information

THERE IS NO WAY TO SELECT FLATPAK ABOVE - 7.5.1.23

### Expected Behavior

I input 1-5 into the cell that has number format set as "General". Nothing happens.

### Actual Behavior

I input 1-5 into the cell that has number format set as "General". The cell number format switches to "Date", breaking my data. Selecting "General" manually converts? the date into numbers (45296 in this example)

**Comment by VladimirProkofiev52** [comment]
Hello! @K0-RR 
I've checked the issue you described, and I want to point out that it's not an error. For example, the Excel editor exhibits similar behavior.

If you need to input '1-5' into a cell, you should change its format to 'text.' Otherwise, the editor will try to interpret it as a date.

If you have any further questions, please feel free to let me know.
