### ISSUE TITLE
Proposal to Add New Financial Formulas to Spreadsheet Editor

### ISSUE THREAD

**Issue by eSkry** [ONLYOFFICE/DesktopEditors#1588]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

**Issue:** The spreadsheet editor lacks sufficient formulas or the existing ones do not consider all necessary parameters for yield calculation.

**Description:** Manually writing simple yield formulas is required to calculate investment returns, especially for bonds. Additionally, there is a need to calculate compound yield, which involves iterating over dates, date ranges, etc.

**Proposal:** Add additional yield calculation formulas to the financial formulas category. Required formulas are described here: ([PDF File](https://fs.moex.com/files/6908/))

**Comment by rsnegirev** [comment]
Hi @eSkry 

Can you please specify any of this formulas? I mean maybe some examples from other editors.

Because we usually don't create unique functions to make each file more compatible between different editors.

Also in the next major version will be release a new feature with creating users custom formulas.
