### ISSUE TITLE
show source of cliparts

### ISSUE THREAD

**Issue by lhpitn** [ONLYOFFICE/DesktopEditors#209]
**Do you want to request a *feature* or report a *bug*?**
feature

please show the source and rights of the cliparts when adding them.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Edition Version 5.2.83.480
(please make this copiable)
on windows 10 64bit (of cause with 64bit version of ONLYOFFICE)

**Comment by Rita-Bubnova** [comment]
Hello, @lhpitn.
In order to see information about where to get images in the ClipArt plugin, you need to click on the bottom of the ClipArt button -> select the "About" item. The window "ClipArt" opens, you can click on the link "Open Clip Art Library" to view more detailed information (including the License).

If this information is not enough for you, please indicate what other information you need, please.
