### ISSUE TITLE
Let windows be handled by the window manager

### ISSUE THREAD

**Issue by Virtheon** [ONLYOFFICE/DesktopEditors#216]
**Do you want to request a *feature* or report a *bug*?**
I'm not sure. A feature, the lack of which makes the application look like it has a bug.

**What is the current behavior?**
The application has its own styled window buttons (e.g. Close, minimise, maximise), similar to buttons in Windows, regardless of how window decorations and buttons are configured.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
While this is not my OS, here is an image I found online demonstrating the issue I have.

![ZfQuW00 - Imgur](https://user-images.githubusercontent.com/48177507/55296831-443eb800-5462-11e9-80cb-cf97ce64bdb7.png)

Note how, rather than the left styled buttons Ubuntu Unity usually has, the buttons are on the right, styled like in Windows.

**What is the expected behavior?**
For the application buttons to conform to window manager/OS styles.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
The latest version. Linux, though I've only personally tested it on KDE. I don't know, but I would not guess so.

**Comment by janxkoci** [comment]
I can confirm this issue **on Linux** (I use elementary OS, which has close button on the left and maximize on the right, with no minimize button). I have found screenshots of OnlyOffice on macOS where the buttons are mac-style as expected, so this issue is really Linux-specific.

The problem is that on Linux there is a lot of different window managers, while on Windows and macOS there is only one, so making it custom-fit for those platforms is easy.

Maybe there is some freedesktop specification to check or listen to, but I'm not a dev so I know very little about this. However I know that cross-platform apps like Chromium or Firefox can usually get it right (although my firefox has both buttons on the left right now, so not always), so it should be doable at least in principle.

**Comment by matveevms** [comment]
We can suggest that you launch the editor with the flag `--system-title-bar`. In this case, the editor window will inherit the system interface (to disable this mode, run the application with the flag `--custom-title-bar`).

**Comment by ShockwaveNN** [comment]
Those flags already aviable in v7.0.0 and I think in earlier version either

So I'm closing this issue

There may be some troubles with some specific window manager, but better to create new issues

**Comment by Batwam** [comment]
Could this be added as an option in the Settings rather than a hidden flag please?

**Comment by matveevms** [comment]
Hello, @Batwam 
Hello. Could you create a new issue for this feature request?

**Comment by patricknelson** [comment]
For those installing it via Flatpak in KDE: This seems to work universally if you add the `--system-title-bar` option suggested by @matveevms above into the shortcut in the KDE Menu Editor (pictured below). Quick way to get to that option is to just search it in the application launcher and right-click on ONLYOFFICE and then select "Edit Application..."

Launching it via double clicking on a document or when directly launching via the ONLYOFFICE shortcut all use the system title bar now.

<img width="2154" height="1291" alt="Image" src="https://github.com/user-attachments/assets/da83851b-e912-4e3d-93a5-1d16c41db87b" />
