### ISSUE TITLE
[Feature Request] Image Watermark on Document editor

### ISSUE THREAD

**Issue by ipproductions** [ONLYOFFICE/DesktopEditors#251]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Can't set image watermark or page background on Doc editor

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
5.3.95.61

**Comment by falling-star** [comment]
@ShockwaveNN I see that the watermark feature is released. Can we pass watermark text / image url as part of DocumentServer editor Config object ? Also watermark can't be removed in the editor/canvas, right ?

**Comment by ShockwaveNN** [comment]
I mean those watermarks, we added them in 5.4 and released.
![image](https://user-images.githubusercontent.com/668524/71468091-ea430700-27d5-11ea-90c9-c64d1de67a06.png)
But those watermarks can be deleted

I'm close this issue, since we released Waterkark
But for your problem @falling-star we are working on non-removable watermark and according to my info - those watermark already working with DocumentServer + Nextcloud
If you using some other solution - please crate separate issue
