### ISSUE TITLE
UI font size should be configurable

### ISSUE THREAD

**Issue by janlimpens** [ONLYOFFICE/DesktopEditors#262]
... or at least it should take into account the system's font size.
Here on my mac, UI font size is something like 12 or 14 pt and Oo's about 9 or 10 pt. It is very difficult to read for me.

**Comment by Rita-Bubnova** [comment]
Hello, @janlimpens.
Thank you for your enhancement.
I created a new issue 42930 in our private issue tracker.
We will discuss this with our team.

**Comment by vladikoles** [comment]
I confirm this problem for Ubuntu 18.04.5 LTS (Gnome Shell 3.28.4) deb, snap, appimage.
The user interface at FullHD resolution is very difficult to work even on 21.5'' screens and almost impossible on 15.6'' screens.
Better to adjust the UI font size and even choose a typeface.

**Comment by LuckySpecialist** [comment]
Hi @rumatoest!
Well, maybe you are a designer and can offer a solution that will suit everyone?
If on business, then there are no plans to work in this area.
At the moment, the application has an interface scaling in the range of 100-500% (if we talk about choosing a small/medium/big font size), do you need more?
P.S. You didn't provide any information about your system, its scaling settings. Also, there are no screenshots from you where we can see how terrible the font looks that you are not satisfied with.

**Comment by LuckySpecialist** [comment]
Hi, @rumatoest!
Well, I understand what you're talking about, but still there is no answer to the main question.
What about interface scaling option in the range of 100-500%?

**Comment by amorozov** [comment]
It seems I have understood the main inconvenience/disappointment.

When one opens a file in OnlyOffice Desktop Editor, it doesn't provide access to "General" application settings which allows to configure the application UI scale, because "File -> Settings" is replaced with "File -> Additional parameters" which corresponds to settings for a particular type of file (a document, a worksheet etc).

Both modes have "Scale" option. In general "Settings" mode it corresponds to Interface scale, while in file mode it corresponds to content scaling. Indeed this may lead to a user's frustration, I've just seen that :-)

To configure UI fonts one has to close all currently opened files, and only then "File -> Settings" become accessible.

As an additional task I would mention an automatic scale detection, which is absolutely necessary when OnlyOffice DE runs simultaneously on multiple monitors with different DPIs. Nowadays such a configuration becomes quite a popular  (e.g. when an external monitor is attached to a notebook, or a desktop with two different monitors etc).
Probably, OnlyOffice DE should receive scale information from Operating System or Desktop Environment settings.
