### ISSUE TITLE
Cannot close the window on win10

### ISSUE THREAD

**Issue by smichea** [ONLYOFFICE/DesktopEditors#301]
I have the following bug on win 10 with ONLYOFFICE Desktop Editors version 5.4.2.30

When i click the cross icon on the top right of the window it has no effect.

Congratulation for your work !

**Comment by Rita-Bubnova** [comment]
Hello, @smichea.
Is this problem reproducing regularly?
Can you describe the steps to reproduce the problem?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by NKSHV** [comment]
Hi I have the same issue. I can't close onlyoffice by clicking "x". I can only kill it in task manager. Windows 10 64. 
p.s. since this issue is closed should I make a new one? Sorry don't know how github works

**Comment by Rita-Bubnova** [comment]
Hello, @NKSHV.
Same questions as for user before:
Is this problem reproducing regularly?
Can you describe the steps to reproduce the problem?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by crlorentzen** [comment]
I don't know if this is the same issue that was posted about here, but my mother encountered this or a similar issue.
She just recently installed ONLYOFFICE as a replacement to LibreOffice. I suggested it since it is more similar to MS Office and is supposed to be better at MS Document formats due to, If I understand correctly, the use of the OOXML format internally, instead of doing format juggling like Libre/OpenOffice.

## Discovery

She was working on updating a docx (Word 2007-365) that was originally created in LibreOffice. 
- When she tried to save, the file she was updating in ONLYOFFICE, she encountered an error: "An Error has occurred while saving the file."

- After this error she tried the close the document tab, and/or the entire window one or two results were seen; either the button shows a click action but doesn't close, or if it offers to save she clicked yes and encountered the same error.
  - If one gets the save offer one can say no and ONLYOFFICE will close
  - If one says yes to the save offer one will get the same error. And we can try to close the window again.
  - If there is no save offer, which will happen after a few trials, then the window won't close and must be killed (Task Manager/taskkill)
- The lost file will be available in the Recover files section when starting ONLYOFFICE again, trying to save these will show the same issue that caused them to be lost. 

## Bug Description
Error while trying to save a docx document originally created in LibreOffice (or elsewhere) and editted in ONLYOFFICE. After multiple attempts to save when closing ONLYOFFICE, window stops offering to save and is not closeable.

![image](https://user-images.githubusercontent.com/25350890/94882046-e3b48080-0434-11eb-9b09-e5cd95f97eb8.png)

## Reproduction
- Tested on
  - Windows 10 Pro 1503, 1904, and 2004 (Also Home)
  - ONLYOFFICE Desktop Editors version 5.6.4.20
- File used in reproduction: 
[test.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/5315697/test.docx)
- Video to gif reproduction: 
![test.gif](https://user-images.githubusercontent.com/25350890/94883813-95ee4700-0439-11eb-8618-ece1392b1f5a.gif)


1. Open test.docx with ONLYOFFICE
1. Make a change to the document, I select the first line and hit Ctrl-E to center the line
1. Attempt to save the file. Encounter error.
1. Attempt to close the window/tab. Say yes to save (may require more than one time)
1. Attempt to close the window/tab. Encounter failure to close either the tab or the ONLYOFFICE window.

I hope that the contrived example can help discover what is getting stuck in ONLYOFFICE.

**Comment by ShockwaveNN** [comment]
@crlorentzen Hi, thank you for very detailed report.

We do not sure it's the same issue as previous authors in this thread, since no one answered for any questions, I think it's better to create new issue with your awesome report, than using this old.
Thank you

**Comment by crlorentzen** [comment]
@ShockwaveNN understood. I will clone my report into a new issue.
Thanks
