### ISSUE TITLE
[Bug] Macros right click menu doesn't work

### ISSUE THREAD

**Issue by hope-full** [ONLYOFFICE/DesktopEditors#310]
**Steps to reproduce:**
1.On linux open macros editor (Plugins > Macros)
2.Switch to another program/window
3.Switch back to Onlyoffice
4.Right click in the macros editor

**Actual result:**
Nothing happens

**Expected result:**
The right click menu should open

**Comment by maruacat** [comment]
Hello @hope-full 
Sorry for the long wait. The problem described in the issue was indeed in older versions of the editor, I was able to reproduce it in version 6.0.0, but the problem is not reproduced in the latest released version 7.4.1.
Can you please tell me if this problem is reproduced in version 7.4.1?
Thank you for your feedback.
