### ISSUE TITLE
[BUG] A weird bug after installation of the NVIDIA driver.

### ISSUE THREAD

**Issue by TheFuzzStone** [ONLYOFFICE/DesktopEditors#324]
A weird bug after installation of the NVIDIA driver.

System: Manjaro Linux
Kernel: 5.4.18
DE: KDE
Nvidia Driver: video-hybrid-intel-nvidia-440xx-prime (440.59)

Screenshots:

![2020-02-13_11-29](https://user-images.githubusercontent.com/16173361/74421910-b2efee80-4e45-11ea-8939-52332704a08c.png)
![2020-02-13_11-28](https://user-images.githubusercontent.com/16173361/74421917-b4211b80-4e45-11ea-8dcf-95e9f010a2ac.png)
![2020-02-13_11-48](https://user-images.githubusercontent.com/16173361/74422085-ec285e80-4e45-11ea-8f8f-bc23cc04f395.png)

---

How can I fix this?

**Comment by XDmitryK** [comment]
Hi you can give more information  about your system? (PC or Laptop, Hardware information, resolution display)

**Comment by TheFuzzStone** [comment]
@XDmitryK 

Laptop: Xiaomi Notebook Pro
Kernel: 5.4.18-1-MANJARO 
Desktop: KDE Plasma 5.17.5 
CPU: Quad Core: Intel Core i7-8550U 
Graphics: 
Device-1: Intel UHD Graphics 620
Device-2: NVIDIA GP108M [GeForce MX150] driver: nvidia v: 440.59
Display: x11 server: X.Org 1.20.7 driver: modesetting,nvidia resolution: 1920x1080~60Hz
OpenGL: renderer: GeForce MX150/PCIe/SSE2 v: 4.6.0 NVIDIA 440.59

**Comment by XDmitryK** [comment]
Unfortunately, we still cannot reproduce this problem due to the lack of a laptop with Nvidia graphics
As soon as something like this is available, I will write in this thread

**Comment by TheFuzzStone** [comment]
A few minutes ago I installed an update 5.5.1.78 -- the problem has not been solved.

**Comment by TheFuzzStone** [comment]
The problem was solved on its own with the Plasma update.

**Comment by devkamiki** [comment]
Hello,
Apologies for reopening this, but this question gets to me, twice. 
Before today I haven't noticed it's actually the NVIDIA driver that makes a difference, because I had installed OnlyOffice after the driver, so I was thinking about its windows manager issue.
Yesterday I re-installed and when I haven't get my Nvidia Driver, OnlyOffice display was quite normal. But after the driver installed and GPU gets to work, the window became extremely large in scale, and I have a screenshot:

![Image](https://github.com/user-attachments/assets/fcf746ec-1bf4-4fe5-8191-1ab7a6d50889)

OS: This happens both to Manjaro and EndeavourOS
Kernel: 6.14.3-arch1-1 (64bit)
DE: both to GNOME and KDE Plasma
Driver Version: 570.133.07

**Comment by devkamiki** [comment]
Ooh, this problem goes away if I use Wayland.
Happens on X11 only
