### ISSUE TITLE
Date before 1900 not handled correctly

### ISSUE THREAD

**Issue by stweil** [ONLYOFFICE/DesktopEditors#370]
ONLYOFFICE currently cannot handle dates before 1900 (tested with ONLYOFFICE in Nextcloud and with Desktop editor  version 5.5.1 for macOS).

When opening a table which was created by ~~Excel~~ LibreOffice or other third party software and stored in XLSX format, such dates are shown as `##########`. Internally such dates have a negative value (that might be the reason why they are handled wrongly), and it is possible to do calculations like adding a sufficiently large number to get a date in the supported range (with a positive value). Adding a value which results in `0` shows the date `00.01.1900` which is obviously wrong. 

Entering a date like `1.1.1900` (German locale) works as expected and uses the date format. Entering `1.1.1899` accepts the entry as a string instead of a date.

**Comment by Rita-Bubnova** [comment]
Hello, @stweil.
Can you attach file created by MS Excel?

**Comment by stweil** [comment]
The attached file was created by LibreOffice and stored as xlsx:
[date.xlsx](https://github.com/ONLYOFFICE/DesktopEditors/files/4523285/date.xlsx)

Column A contains strings 01.01.1890, 31.12.1899 and 01.01.1900.
Column B contains the same values as dates.

I just learned that Excel also has problems with those dates, but it is possible to create xlsx files with such dates using LibreOffice or other third party software (e. g. Python libraries).

**Comment by Rita-Bubnova** [comment]
@stweil, you are right, that Excel also так же отображает дату 01.01.1890. Since XLSX is the main format for us, to ensure compatibility with MS Excel, we also display such dates as a negative value.

Our team needs to consider the possibility of supporting dates like 01.01.1890, without compromising compatibility with MS Excel.

**Comment by stweil** [comment]
That would be great and highly desirable, especially for the Open Document file format.

**Comment by Rita-Bubnova** [comment]
We discussed this issue with our development team (issue 45330 in our internal issue tracker). 
As a result, it was decided to keep current behavior.  As I mentioned earlier, this is to ensure compatibility with MS Excel (since XLSX is the main format for us).

We may change it in future, but currently have no perfect solution.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
