### ISSUE TITLE
These projects need build / installation instructions.

### ISSUE THREAD

**Issue by EliteTK** [ONLYOFFICE/DesktopEditors#4]
These projects are released under the AGPL-3.

A clause of this license states that any source must also be accompanied with adequate installation instructions to inform potential users of how the project should be built.

So, very simply: These projects need to list build and runtime dependencies, as well as some rudimentary build instructions.

**Comment by maxkadushkin** [comment]
yes, the instructions is preparing

**Comment by jirutka** [comment]
I’d like to create [Alpine Linux](https://alpinelinux.org/) package for OnlyOffice, but hard to do it without any instructions how to build the project.

**Comment by lastweakness** [comment]
Has there been any progress in this issue?

**Comment by AsavarTzeth** [comment]
The OnlyOffice developers recently reached out on the flatpak mailing list (flatpak@lists.freedesktop.org). Among other things, they ask for assistance on packaging their application. I thought as an experienced flatpak packager I could perhaps help them create an initial build manifest.

However, due to the complete lack of build instructions I am finding this nearly impossible. The OnlyOffice team really should solve this issue and in the process, help us help them.

Also see  #86

**Comment by vatterspun** [comment]
> However, due to the complete lack of build instructions I am finding this nearly impossible. The OnlyOffice team really should solve this issue and in the process, help us help them.

If this has been on their TODOLIST since 2016, that might be a statement on the kind of community participation they're looking for.  

It's a shame too because, unless there's something we're missing and it's really a quite simple build process, they're not going to see community-contributed bugfixes and other useful software changes.  Part of the reason to develop an open project is the potential for that kind of involvement.

**Comment by ShockwaveNN** [comment]
Great news guys, we got instruction how to build DesktopEditors
https://github.com/ONLYOFFICE/build_tools#desktop-editors

Currently build work only on Ubuntu 14.04 (you can use Docker tro build it), but build result should be work on all Ubuntu versions, possible CentOS.

Please feel free to report any build issues at https://github.com/ONLYOFFICE/build_tools repo
