### ISSUE TITLE
PDF Viewer bugs, enhancements, and others...

### ISSUE THREAD

**Issue by gczark** [ONLYOFFICE/DesktopEditors#412]
I recently got my hands on with this software. Although having an account for MS Office, I find something promising with the software which makes me planned to move to your free license. A decluttered experience unlike MS which most of the time nonresponsive.

BUGS:
- pdf viewer doesn't show bookmarks and notes of the document.
- viewing a pdf is significantly slower compared to how fast SumatrPDF handles big documents.
- links from table of contents does not work.
- some files fails to open. (a book pdf saved as docx with MS, which apparently cannot be handled by ONLYOFFICE)

ENHANCEMENTS:
- features including bookmarking, highlighting and inserting texts to pdf.
- morph in powerpoint, other transitions is an actual trash.
- print preview dialog.
- pin to quick access toolbar.
- plugins store.
- latex equations (ex. \pm for ±).

UI: (opinion)
- remove ONLYOFFICE text branding in the tab, and leave the icon.
- remove borders from the main window.
- option to use without tabs.
- revamped ONLYOFFICE tab.

**Comment by ShockwaveNN** [comment]
Hi, we glad that you are find our product interesting
But please note this is not a forum, but issue tracker and you have 14 different problems and enhancements in your issue, so I don't think it will be productive to discuss all in one here, because it will be massive and definitely will be misunderstanding between separate issues.

There is some issues already exists, f.e. Print Preview https://github.com/ONLYOFFICE/DesktopEditors/issues/263 

For some we have plans but no exact dates, like plugins store.

And some of them we need to investigate, like `some files fails to open.` - this is not right and we'll try to fix it

So to have clear discussion for each problem - create separate issue for each problem and enhancement

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by ShockwaveNN** [comment]
Please read my responce carefully - print preview is discussed in #263 issue

This issue was closed not because ideas is bad, but because making one issues with tens of ideas is counter-productive

**Comment by maravento** [comment]
> Please read my responce carefully - print preview is discussed in #263 issue
> 
> This issue was closed not because ideas is bad, but because making one issues with tens of ideas is counter-productive

thanks. I appreciate your effort. Hopefully one day the "print preview" thing will be solved
