### ISSUE TITLE
PDF looks bad on Linux

### ISSUE THREAD

**Issue by ngustavo** [ONLYOFFICE/DesktopEditors#43]
I want to request a bug fix and an improvement.

When you print a Document to PDF and open it on Chrome, the fonts look horrible. And it takes so long to generate the PDF in comparison to Google Docs and LibreOffice. I think it would be a better user experience if you added an Export to PDF button.

I'm using 4.2.5.312 on Linux Mint 18.1 based on Ubuntu 16.04 64-bit.

**Comment by maxkadushkin** [comment]
'Save as' option make export to PDF. menu File -> Save as

**Comment by maxkadushkin** [comment]
'Print to pdf' and 'Save as pdf' are different actions. in first one, app doesn't know about the output format. virtual printer, that user chose, keep data from the app to pdf format and quality of the result depend on printer settings (printer dpi in your case). because that, such file will be good for printing, not for viewing. for better viewing in a system viewer you should choose printer dpi compared to system dpi.
Use Save as PDF if you want to have PDF copy of document.

**Comment by ngustavo** [comment]
I still have font issues though. I'm using Arial and Courier New. Some Arial paragraphs got Courier style.
I already sent my papers to the professor. I used LibreOffice to export to PDF.

Thank you. Cheers.

**Comment by aditiapratama** [comment]
I don't know if it's okay to put it here. The generated hyperlink in pdf is not clickable. I open the file in libreoffice and export it to pdf then it's works.
Here I attach the pdf file generated from onlyoffice `>>` [**open_link_pdf.pdf**](https://github.com/ONLYOFFICE/DesktopEditors/files/1033090/open_link_pdf.pdf)

thanks

**Comment by ShockwaveNN** [comment]
I think original issue should be fixed, so I'm closing this issue. If it's still actual - feel free to create new issue
