### ISSUE TITLE
I can't enable gpu acceleration with --enable-gpu-rasterization parameter

### ISSUE THREAD

**Issue by pemmoura** [ONLYOFFICE/DesktopEditors#445]
**Do you want to request a *feature* or report a *bug*?** 
Feature

**What is the current behavior?** 
I can't enable gpu acceleration for chromium with parameter --enable-gpu-rasterization, which makes the application run very slow on a high resolution display.

**What is the expected behavior?**
Run the application with: `onlyoffice-desktopeditors --enable-gpu-rasterization ` and the parameter is passed to chromium.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Version 5.6.0, Debian GNU/Linux with kernel 5.7.

**Comment by matveevms** [comment]
Hello, @pemmoura 
Sorry for such a late reply. 
Please tell me if the problem is repeated on new versions of the application, when working on screens with a higher resolution?

**Comment by kde-yyds** [comment]
so can we enable opengl for cef? i cannot see fps when GALLIUM_HUD=fps is set and animations are not very smooth

**Comment by kde-yyds** [comment]
any updates?

**Comment by FlorianHeigl** [comment]
@pemmoura hi, i have no idea why they don't add this rather simple request, but if the chromium binary is launched in from outside onlyoffice you could use /etc/alternatives or /usr/local/bin to add a wrapper named chromium and let that one launch something like ${@} --enable-gpu-rasterization.

@matveevms you had written that questions  would be answered, since over a year has passed it would be nice to see a reply at some point - after all this would make for a much faster ui :-)
