### ISSUE TITLE
OnlyOffice stays in FullScreen after a SlideShow

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DesktopEditors#463]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
On Linux, OnlyOffice Presentation stays in FullScreen after a SlideShow

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- On Linux, play a slidehow and exit
=> OnlyOffice stays in FullScreen, there is no button to close or minimize the window

**What is the expected behavior?**
OnlyOffice should come back in a window mode, where you can resize your window or minimize it

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
5.6.4 on Debian 11 Bullseye

**Comment by Rita-Bubnova** [comment]
Hello, @parrenin.
Thank you for report.
I can confirm - this is bug, issue 46591 in our private issue tracker.

**Comment by PatLabGit** [comment]
The .AppImage does **not** have this bug. Behavior is as expected (exit properly from the full screen slide show with the last click or the Esc key) 
ONLYOFFICE Desktop Editors version 5.6.4.20

**Comment by Iangh59** [comment]
It does go back into window mode second time of asking. First time, press escape and it stays in fullscreen. Whilst there press play bottom left to go back into slide show, then 'esc' and back to window mode.

I tried the appimage and it takes forever (mins) to open on Kubuntu 20.04. Even then there is the same issue re staying in fullscreen.

Really like the OO interface but keep going back to WPS because it works. I'm hopeful that one day I will stay with OO.

**Comment by Rita-Bubnova** [comment]
Issue 46591 fixed (https://github.com/ONLYOFFICE/desktop-apps/commit/0b1de67e26188ddc7ac2708afa62739570d14afd) in future major release.

**Comment by ShockwaveNN** [comment]
ONLYOFFICE Desktop Editors version 6.0.2 is released for some time, this issue should be closed

**Comment by parrenin** [comment]
Great to see this has been fixed.
One less friction point with OnlyOffice.
