### ISSUE TITLE
[Bug] Recent Folders does not open correct folder

### ISSUE THREAD

**Issue by nlogozzo** [ONLYOFFICE/DesktopEditors#528]
**Do you want to request a *feature* or report a *bug*?**
Bug

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open Local File -> Click a recent folder -> Ex: /home/user/Docs/A will open Ex: /home/user/Docs/B . Choosing another folder from the list for example /home/user/Docs/C will also open Ex: /home/user/Docs/B. Once let's say a document from /home/user/Docs/A is opened then going to Open Local File -> and clicking ANY folder will open the /home/user/docs/A folder

**What is the expected behavior?**
The correct folder in the list is opened in the file chooser dialog 

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Tested on Ubuntu 18.04 on V6.1.0

**Comment by matveevms** [comment]
Hi, @nlogozzo 
Could you please record a video of the problem?

**Comment by HectorB-2020** [comment]
@nlogozzo , seems like something similar is observed in Windows version as well.

I'll try to explain further.
Open local file ->  Recent folder

actually contains list of recently accessed folders.

However regardless on what you click on in this list, only the recently opened folder will open.

Assume now you have "Desktop" and "Documents" in the list of recent folders.
Click "Browse" and find a file let's say among "Downloads". "Downloads" will duly appear in the list of recent folders.

Since this moment whatever you click on in the list of recent folder will always open the folder "Downloads".

**Comment by matveevms** [comment]
Hi, @HectorB-2020 
Indeed, for Windows there is such a problem. Could you create a separate issue for your system so that in the future you can track the solution to this problem.

@nlogozzo, I still cannot reproduce your problem on ubuntu 18.04

**Comment by nlogozzo** [comment]
It occurred to me on ElementaryOS with the Pantheon desktop environment. When I switched to KDE Plasma, the issue went away. I have no switched back to Windows so I don't have any videos of the issue.
