### ISSUE TITLE
Provide an RPM for SUSE

### ISSUE THREAD

**Issue by maydayv7** [ONLYOFFICE/DesktopEditors#681]
As in title, please provide an .rpm to install OnlyOffice on openSUSE and SUSE Linux
The current one only works with RedHat

**Comment by ShockwaveNN** [comment]
We provide snap, flatpak and AppImages

Is there any particualr reason why this is no good alternative for native rpm?

**Comment by maydayv7** [comment]
This is as there is no auto-update with ApppImages, flatpak OnlyOffice has some issues with the .desktop file and OS integration, and snapd does't have an official package on openSUSE.

**Comment by matveevms** [comment]
Hello, @maydayv7 
Thank you for enhancement.
This is bug 51549 in our private issue tracker.

**Comment by utk-dev** [comment]
https://snapcraft.io/onlyoffice-desktopeditors

Doesn't this one work with OpenSuse (It's official)?

**Comment by ShockwaveNN** [comment]
@utk-dev This is our official snap

Topic starter meant that `snapd` daemon is not official by OpenSUSE, not our product

**Comment by iMprjkt** [comment]
Any delivery time frame for this?

Currently installed the RPM (Version 7.0.2) from the site (CentOS and RHEL) works fine despite ignoring the boost-system package dependency. The dependency is provided by libboost_filesystem1_79_0 package (currently on OpenSUSE Tumbleweed)
The application works fine.

**Comment by ShockwaveNN** [comment]
Sorry, cannot provide any time frame, because I think snap/flaptak/appimage cover most of user cases

If you really need this to be done - better contact sales@onlyoffice.com

**Comment by the4anoni** [comment]
any update on this?

**Comment by adelphi23** [comment]
@ShockwaveNN - I've been lurking on this since its beginning as I am appreciative of the difficulties in prioritizing open source development. Also, I have been a happy Fedora user for a while so I was not on a rush to use it in my Tumbleweed installs. Yet, I've been using the latter as my main driver and do miss the integration of the regular rpm install. 
Is there any expectation for an opensuse friendly rpm at this point? It is ok to say no, but I do need to set expectations since this would be installed in the VMs/machines I use in the university so it would be great to learn whether I should aim for a Fall24 install or use workarounds.
Thanks for your great work and support!

**Comment by ENTPRESTIGIOUS** [comment]
I also want to see a native version running on openSUSE!

**Comment by agolybev** [comment]
Hi, ONLYOFFICE provides DesktopEditors for OpenSUSE since version 7.4.1. See the package in the Release assets

**Comment by ENTPRESTIGIOUS** [comment]
> Hi, ONLYOFFICE provides DesktopEditors for OpenSUSE since version 7.4.1. See the package in the [Release assets](https://github.com/ONLYOFFICE/DesktopEditors/releases)

But that's for SUSE 12 which is an old build right?

**Comment by heatray** [comment]
no

**Comment by NikitaBeloglazov** [comment]
Is there a repository for this RPM? There is for CentOS, but not for SUSE
