### ISSUE TITLE
No snap package in Github issue template

### ISSUE THREAD

**Issue by mikhailnov** [ONLYOFFICE/DesktopEditors#776]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

0

### Expected Behavior

when filing a new issue on github, it is not possible to choose a snap package

### Actual Behavior

![image](https://user-images.githubusercontent.com/15802528/144749805-3de073e3-2fc2-4f3d-8a20-976cea9097f8.png)

**Comment by ShockwaveNN** [comment]
Hi, that's because any snap related issues should be reported at [another repo](https://github.com/ONLYOFFICE/snap-desktopeditors)

So before reporting you should check deb/rpm version if possible and if this issue is actual to only snap - it goes to another repo. If not - it stays in main repo

**Comment by mikhailnov** [comment]
Well, I do not see sense to report issues like https://github.com/ONLYOFFICE/DesktopEditors/issues/777 into snap-desktopeditors, it is confusing

**Comment by ShockwaveNN** [comment]
> Well, I do not see sense to report issues like #777 

Yeah, your right, it's a little bit confusing

But issue #777 has nothing to do with snap itself, this problem is actual for any of our products, so logic will be - if this problem not `snap-only` it goes to this, DesktopEditors repo, so it need to be checked on `deb` (it may be done by us, if you have not deb-supported OS and issue is not very complicated, like yours #777)
