### ISSUE TITLE
Compatibility Error

### ISSUE THREAD

**Issue by Juniorsnet** [ONLYOFFICE/DesktopEditors#797]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (RPM package)

### Version information

6.4.2.17

### Expected Behavior

The text in tables must appear correctly

### Actual Behavior

the text in the tables are not render correctly, this document was created with ms office, downloaded, opened with onlyoffice then saved.
onlyoffice on windows work perfectly the text is show

### Reproduction Steps

Open attached document

### Additional information

I m using Manjaro x64

The file is:

[S2](https://filedn.com/lsGYnWmDn67jepFm0Ehk7z0/S2.docx)

**Comment by Wo1fgang** [comment]
Hi @Juniorsnet 

I opened your file on 6.4.2 (AppImage) version of ONLYOFFICE and saw what's the problem
Then I installed 7.0.0 and noticed that the problem is now gone

But just in case, the problem is still occurring on your PC, could you please provide screenshots highlighting which text is not rendered? 
Thank you.

**Comment by Juniorsnet** [comment]
Hi @ShockwaveNN indeed the problem with 7.0.0 is gone.
Thank you

**Comment by ShockwaveNN** [comment]
@Juniorsnet Thanks for your quick response, I'll close issue in that case
