### ISSUE TITLE
OnlyOffice rewrites .ods to custom format, makes it unreadable for other editors

### ISSUE THREAD

**Issue by panique** [ONLYOFFICE/DesktopEditors#836]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

macOS 10.12 or higher

### Version information

7.0

### Expected Behavior

.ods files that were created with OnlyOffice should be readble with any .ods-compatible program out there

### Actual Behavior

.ods files that were created with LibreOffice can be opened with OnlyOffice, but after being saved with OnlyOffice, they are unreadble/corrupt for LibreOffice.

### Reproduction Steps

TODO

### Additional information

I tried out OnlyOffice 7.0 as it was widely promoted in tech blogs. Now all my business related .ods sheet are corrupt and can only be read with Onlyoffice, but not with Libreoffice, Openoffice or Excel. Absolute horror for any company working with .ods, where ods are shared widely among many people. This has worked fine for years, but was 100% caused by trying out onlyoffice.

As the affected files (all) contain sensitive data, i cannot share them here, but I'm trying to provide a anonymized example soon.

### Emergency workaround

For anybody else having this problem: You can save your work by saving the file to .xls, exporting the file to Excel (!!) and then converting it back to .ods with Excel. The file will be formatted differently, but the numbers are still there.

**Comment by ShockwaveNN** [comment]
Hi, first of all - I'm sorry for your troubles

I think it has something to do with some specific functions that you used in your ods files because I've tried to save several rather simple ods files - and we do not break them for LibreOffice in any way

So we really need those files

If you are able to remove sensitive data from them - it will be great - attach them to this issue, please
But if you are not able - you can send them to files@onlyoffice.com and we'll try to handle your situation

Sorry once again


And I got second thought - could you try to perform opening them and resaving not on macOS but on Windows or on Linux, because this may be macOS specific bug and this is a good place to rule out macOS from this problem

**Comment by ShockwaveNN** [comment]
Sorry, but seems that we didn't receive any file from you, so I don't think we can do anything with this issue or without some additional info from you, I'll close this issue but feel free to comment here and I'll reopen it
