### ISSUE TITLE
OnlyOffice does not assiociate itself as the primary office app 

### ISSUE THREAD

**Issue by zilexa** [ONLYOFFICE/DesktopEditors#879]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Manjaro 21.2.5 (uses Gnome 41.3)
Probably this is an issue with Debian or Ubuntu based systems as well. 

### Version information

7.0.1.37

### Expected Behavior
If you install OnlyOffice _after_ for example LibreOffice (Fresh), you expect OnlyOffice to have taken the file associations and become the default to open when you doubleclick a supported office filetype. 
In `/usr/share/applications/mimeinfo.cache` you expect OnlyOffice to be the first application for each Office filetype.

### Actual Behavior

LibreOffice is still the default application after you install OnlyOffice. 
Notice in `/usr/share/applications/mimeinfo.cache`, OnlyOffice is only added at the end for each Office filetype. LibreOffice is still the first one. 

### Reproduction Steps

0. A clean install of Manjaro Gnome, then uninstalled OnlyOffice since it is installed by default. 
1. Install LibreOffice. 
2. Open the file `/usr/share/applications/mimeinfo.cache` and notice LibreOffice is listed as first application in the list for all Office files.
3. Now install OnlyOffice for example via Add/Remove software or `sudo pacman -S --noconfirm onlyoffice-desktopeditors`.
4. Check  `/usr/share/applications/mimeinfo.cache` again.

### Additional information

Problem: 
This way, when doubleclicking a file that you want to open in OnlyOffice, LibreOffice opens instead. If you want to use LibreOffice only as backup, this is a problem. 

There is no easy way to solve this for ALL filetypes supported by OnlyOffice. For example, you would need to right-click each filetype, whenever you come across it, use Open As and then set the default for that filetype only. 

Note the other way around, if you install OnlyOffice first then LibreOffice, LibreOffice becomes the default app, this is also reflected in `mimeinfo.cache`.
Please fix.

**Comment by ShockwaveNN** [comment]
Hi, I've rechecked your problem on Ubuntu with our official deb package
That I've done:
1. `sudo apt purge onlyoffice-desktopeditors`
2. `cat /usr/share/applications/mimeinfo.cache | grep onl` - there is not a single entry about `onlyoffice`
3. `sudo apt install onlyoffice-desktopeditors``
4. `cat /usr/share/applications/mimeinfo.cache | grep onl` - there is 56 entries for `onlyoffice-desktopeditors.desktop`
Like those one:
```
application/csv=onlyoffice-desktopeditors.desktop;
application/excel=onlyoffice-desktopeditors.desktop;
application/msexcel=onlyoffice-desktopeditors.desktop;
application/mspowerpoint=onlyoffice-desktopeditors.desktop;
```

So if I understand your correctly your problem is not actual for deb package

So I think this problem is for `pacman` package on Arch and this is not our official package, I don't know who made this
I think it's better to contact it's authors

**Comment by ShockwaveNN** [comment]
Yes, there is no Arch or Manjaro native application made by us, ONLYOFFICE, team

We only provide snap, flatpak and AppImage versions for those systems

I don't know about Manjaro issue tracker at all, but I think you should report this issue there

**Comment by zilexa** [comment]
Will do thanks!
Btw it is listed on the OnlyOffice website. I'll start asking on Manjaro forum.

**Comment by ShockwaveNN** [comment]
Yeah, you right it's listed in our site, but most of packs in "ONLYOFFICE Desktop Editors are pre-installed on" are either snap/flatpak/appimage or made by os maintainers

**Comment by KelvinNovais** [comment]
Hello! I had the same problem...

**If you are on Gnome/Nautilus:**

**1. Navigate to the file  you want to change the default association;
2. Right click > Properties;
3. Open With;
4. Select the new application > Set as default.**

I think the problem is more related to GNOME and the system first default application to that file extension. However, I think you could put this information on the documentation to avoid people waste time (as I did) thinking the problem is the OnlyOffice or the Flatpak.

- OS: PopOS 22.04 LTS
- OnlyOffice version: 7.1.1.57
- Flatpak version: 1.12.7

Thank you.
