### ISSUE TITLE
Where to send feedback?  Highlight color dark mode?

### ISSUE THREAD

**Issue by Thermalzombie** [ONLYOFFICE/DesktopEditors#892]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hi I have been trying out Onlyoffice and I like it but there is a couple questions.

I was looking for a document editor with a dark mode/theme and came across Onlyoffice I seen some screenshots and thought it looked promising then I downloading the desktop version for windows 10.

Well it took me an hour to figure out how to turn on dark mode.  I found the dark theme setting in the file > settings menu easy enough but it took me ages to find how to make the page dark.  Until I stumbled upon the hamburger menu who's bright idea was it to put a page color setting in a different location then the theme setting.  Makes no sense to me.

Related to the theming is I cannot find how to change the highlighting color for text when a dark page is enabled.  Is there some setting to change it somewhere.

Also I don't see a Help > About section so I can check what version of the software I have installed.  To check for updates.

Apart from these small issues I have been liking the software I would recommend it to others if there is a solution to the highlight issue.

Also I did look into posting on the forums but was unsure on what section to post in.

Thanks.

**Comment by ShockwaveNN** [comment]
Hi, could you split up this feedback message to different issues, single issue for single problem, so we can handle them properly and isolated, because github is not a feedback forum, it's a place to report isolated issues

And I can answer about About and Versions - it's located in main menu:
![image](https://user-images.githubusercontent.com/668524/164191742-5f3d6f29-8474-4179-8418-226234d241df.png)
