### ISSUE TITLE
[Feature Request] Add save document format (in brackets) as in Windows for Linux

### ISSUE THREAD

**Issue by Xazev** [ONLYOFFICE/DesktopEditors#939]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

![Screenshot_3](https://user-images.githubusercontent.com/11159920/170952959-6fe7d9a4-38b0-4c59-b339-0f9d057c9f0e.png)

**Comment by ShockwaveNN** [comment]
Hm, this is interesting because for me on Kubuntu 20.04 I have format names in this window
![image](https://user-images.githubusercontent.com/668524/173224794-6853ab10-1ef5-49ee-9682-ee888828824d.png)

This is why we ask everyone to fill out issue template with maximum details, not only 'screenshot'

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
